Areas/Templates/Controllers/FormsController.cs
using ExamForms.Manager;
using ExamForms.Models.Accounts;
using ExamForms.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExamForms.Areas.Templates.Controllers
{
    [Area(nameof(Templates))]
    public class FormsController : Controller
    {
        private readonly TemplateManager templateManager;
        private readonly QuestionManager questionManager;
        private readonly FormsManager formManager;
        private readonly UserManager<ApplicationUser> userManager;

        public FormsController(TemplateManager templateManager
            , QuestionManager questionManager
            , FormsManager formManager
            , UserManager<ApplicationUser> userManager)
        {
            this.templateManager = templateManager;
            this.questionManager = questionManager;
            this.formManager = formManager;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            FormViewModel formViewModel = new FormViewModel();
            formViewModel.Questions = await questionManager.GetQuestionsByTemplateIdAsync(id);
            formViewModel.TemplateId = formViewModel.Questions.FirstOrDefault().TemplateId;
            return View(formViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitForm(FormViewModel model)
        {
            await formManager.SaveFormAsync(model, User.Identity);
            return View();
        }

        public async Task<IActionResult> DetailsTemplateForm(int formId, int templateId)
        {
            FormViewModel form =  await formManager.GetFormByIdAsync(formId, templateId);
            return PartialView("~/Areas/Templates/Views/Shared/_TemplateFormDetailsModal.cshtml", form);
        }
    }
}

Areas/Templates/Controllers/QuestionController.cs
using ExamForms.Constants;
using ExamForms.Manager;
using ExamForms.Models;
using ExamForms.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;

namespace ExamForms.Areas.Templates.Controllers
{
    [Area(nameof(Templates))]
    public class QuestionController : Controller
    {
        private readonly QuestionManager questionManager;

        public QuestionController(QuestionManager questionManager)
        {
            this.questionManager = questionManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SaveQuestionModal(int questionId, int templateId)
        {
            QuestionViewModel model = new QuestionViewModel();
            model = await questionManager.GetQuestionByIdAsync(questionId);
            return PartialView("~/Areas/Templates/Views/Shared/_TemplateQuestionAddModal.cshtml", model);
        }

        public IActionResult AddQuestionCheckbox(int questionType)
        {
            QuestionViewModel questionViewModel = new QuestionViewModel();
            return PartialView("~/Areas/Templates/Views/Shared/_AddQuestionCheckboxModal.cshtml", questionViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddTemplateQuestion(QuestionViewModel model)
        {
            if (model.QuestionId == 0)
                model.QuestionId = await questionManager.AddTemplateQuestionAsync(model, User.Identity);
            else
                model.QuestionId = await questionManager.UpdateTemplateQuestionAsync(model, User.Identity);

            List<QuestionViewModel> questions = new List<QuestionViewModel>();
            questions = await questionManager.GetQuestionsByTemplateIdAsync(model.TemplateId);

            return PartialView("~/Areas/Templates/Views/Shared/_TemplateQuestionList.cshtml", questions);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTemplateQuestion(int questionId)
        {
            await questionManager.DeleteTemplateQuestionAsync(questionId);

            List<QuestionViewModel> questions = new List<QuestionViewModel>();
            questions = await questionManager.GetAllQuestionsAsync();

            return PartialView("~/Areas/Templates/Views/Shared/_TemplateQuestionList.cshtml", questions);
        }
    }
}

Areas/Templates/Controllers/TemplateController.cs
using ExamForms.Manager;
using ExamForms.Models;
using ExamForms.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Principal;

namespace ExamForms.Areas.Templates.Controllers
{
    [Area(nameof(Templates))]
    public class TemplateController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        public readonly TemplateManager templateManager;
        private readonly QuestionManager questionManager;
        internal readonly FormsManager formsManager;

        public TemplateController(TemplateManager _templateManager
            , QuestionManager questionManager
            , FormsManager formsManager
            , IWebHostEnvironment _webHostEnvironment)
        {
            templateManager = _templateManager;
            this.questionManager = questionManager;
            this.formsManager = formsManager;
            webHostEnvironment = _webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var templates = await templateManager.GettAllTemplateAsync();
            return View(templates);
        }

        public async Task<IActionResult> SaveTemplate(int id, string tab = "Setup")
        {
            TemplateViewModel template = new TemplateViewModel();
            template = await templateManager.GetTemplateByIdAsync(id) ?? new TemplateViewModel();

            var topics = await templateManager.GettAllTopic();
            ViewBag.Topics = new SelectList(topics, "TopicId", "TopicName");
            ViewBag.Tags = await templateManager.GettAllTag();
            ViewBag.ActiveTab = tab;

            template.Questions = await questionManager.GetQuestionsByTemplateIdAsync(id);
            return View(template);
        }

        [HttpPost]
        public async Task<IActionResult> SaveTemplateSetup(TemplateViewModel model, IFormFile? Image)
        {
            if (Image != null)
            {
                string folder = "images/templateImages/";
                folder += Guid.NewGuid().ToString() + Image.FileName;
                string serverFolder = Path.Combine(webHostEnvironment.WebRootPath, folder);
                Image.CopyTo(new FileStream(serverFolder, FileMode.Create));
                model.Image = "/" + folder;
            }

            if (model.TemplateId == 0)
                model.TemplateId = await templateManager.CreateTemplateAsync(model, User.Identity);
            else
                model.TemplateId = await templateManager.UpdateTemplateAsync(model, User.Identity);
            
            return RedirectToAction("SaveTemplate", new { id = model.TemplateId, tab = "Questions" });
            //return Json(new { message = "Success", id = model.TemplateId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTemplate(int id)
        {
            await templateManager.DeleteTemplateAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var template = await templateManager.GetTemplateByIdAsync(id);
            var comments = await templateManager.GetCommentsByTemplateIdAsync(id);
            var likes = await templateManager.GetLikesByTemplateIdAsync(id);

            var templateDetailsViewModel = new TemplateDetailsViewModel
            {
                Template = template,
                Comments = comments,
                LikesCount = likes.Count
            };

            return View(templateDetailsViewModel);
        }

        public async Task<IActionResult> TemplateDetails(int id)
        {
            var templete = await templateManager.GetTemplateAllDetailsAsync(id);
            ViewBag.TemplateStatus = "Read-Only";
            return View(templete);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(CommentViewModel comment)
        {
            var result = await templateManager.AddCommentAsync(comment);
            return RedirectToAction("Details", new { id = comment.TemplateId });
        }

        [HttpPost]
        public async Task<IActionResult> AddLike(LikeViewModel like)
        {
            var result = await templateManager.AddLikeAsync(like);
            return RedirectToAction("Details", new { id = like.TemplateId });
        }

        
    }
}

Areas/Templates/Views/Template/Create.cshtml
@using Newtonsoft.Json
@model ExamForms.ViewModel.TemplateViewModel

@{

}

<style>
    .advance-options .tagify__tag {
        --tag-hover: var(--tag-bg);
    }
</style>

<ul class="nav nav-tabs nav-fill" id="templateTabList" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="template-setup-tab" data-bs-toggle="tab" href="#template-setup" role="tab" aria-controls="template-setup" aria-selected="true">Template Setup</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="template-question-tab" data-bs-toggle="tab" href="#template-question" role="tab" aria-controls="template-question" aria-selected="false">Template Question</a>
    </li>
</ul>

<div class="tab-content" id="templateTabBody">
    <div class="tab-pane fade show active" id="template-setup" role="tabpanel" aria-labelledby="template-setup-tab">
        <div class="pt-3 pb-3">
            @using (Html.BeginForm("SaveTemplateSetup", "Template", FormMethod.Post, new { area = "Templates", id = "templateSetupForm", enctype = "multipart/form-data", @class = "" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="mb-3">
                    <label class="form-label" for="templateTitle">@Html.DisplayNameFor(x => x.Title)</label>
                    @Html.EditorFor(x => x.Title, new { htmlAttributes = new { placeholder = "Template title", id = "templateTitle", @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3">
                    <label class="form-label" for="templateDescription">@Html.DisplayNameFor(x => x.Description)</label>
                    <div class="descriptionEditor"></div>
                    <input asp-for="Description" type="hidden" id="templateDescription" />
                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3">
                    <label class="form-label" for="templateTopic">@Html.DisplayNameFor(x => x.TopicId)</label>
                    @Html.DropDownListFor(model => model.TopicId, (IEnumerable<SelectListItem>)ViewBag.Topics, "-- Select a Topic --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.TopicId, "", new { @class = "text-danger" })
                </div>
                <div class="mb-3">
                    <label class="form-label" for="templateTag">@Html.DisplayNameFor(x => x.Tags)</label>
                    <input class='advance-options form-control' id="templateTags" value=''>
                    <input type="hidden" id="hiddenTags" asp-for="Tags" name="Tags" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="templateTopic">@Html.DisplayNameFor(x => x.Image)</label>
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { id = "editTemplateImage", type = "hidden" } })
                    @Html.EditorFor(x => x.Image, new { htmlAttributes = new { id = "templateImage", @class = "form-control", accept = "image/jpeg, image/png", name = "Image", type = "file" } })
                </div>
                <button type="submit" class="btn btn-primary">Next</button>
            }
        </div>
    </div>

    <div class="tab-pane fade" id="template-question" role="tabpanel" aria-labelledby="template-question-tab">
        <div class="pt-3 pb-3">
            <button id="addQuestionBtn" class="btn btn-outline-success">Add New Question</button>
        </div>
@* 
        <div id="question_list_sortable_placeholder">
            @Html.Partial("~/Areas/Templates/Views/Shared/_TemplateQuestionList.cshtml", Model?.Questions)
        </div> *@
        <div id="question_list_sortable_placeholder">
            <partial name="~/Areas/Templates/Views/Shared/_TemplateQuestionList.cshtml" model="@Model?.Questions" />
        </div>
    </div>
</div>

<div id="addQuestion_modal_placeholder"></div>

@section Scripts {
    <script>
        var tagsFromServer = @Html.Raw(JsonConvert.SerializeObject(ViewBag.Tags));
        var hiddenInput = document.getElementById('hiddenTags');

        var input = document.querySelector('input.advance-options'),
            tagify = new Tagify(input, {
                pattern: /^.{0,20}$/,
                delimiters: ",| ",
                keepInvalidTags: false,
                maxTags: 6,
                whitelist: tagsFromServer,
                dropdown: {
                    enabled: 1,
                    fuzzySearch: false,
                    position: 'text',
                    caseSensitive: false,
                }
            });

        tagify.on('change', function () {
            hiddenInput.value = tagify.value.map(tag => tag.value).join(',');
            updatePlaceholderByTagsCount();
        });

        function updatePlaceholderByTagsCount() {
            if (tagify.value.length == 0) {
                tagify.setPlaceholder(`Maximum 6 tags can be added`);
            } else {
                tagify.setPlaceholder(`${6 - tagify.value.length} are left`);
            }
        }

        updatePlaceholderByTagsCount()

        // ---------------- EDITOR -----------------------
        const quill = new Quill('.descriptionEditor', {
            theme: 'snow'
        });

        quill.on('text-change', function (delta, oldDelta, source) {
            var editorContent = quill.root.innerHTML;
            $('#templateDescription').val(editorContent);
        });

        // -------------- TABLE DRAGGER ------------------
        
    </script>
}

Areas/Templates/Views/Template/Details.cshtml
@model ExamForms.ViewModel.TemplateDetailsViewModel

@{
    ViewData["Title"] = "Template Details";
}

<div class="container my-5">
    <div class="row">
        <!-- Template Image and Information -->
        <div class="col-md-6">
            <img src="@Model.Template.Image" alt="Template Image" class="img-fluid rounded shadow-sm" style="max-height:400px; object-fit:cover;" />
        </div>

        <div class="col-md-6">
            <h2 class="mb-3">@Model.Template.Title</h2>
            @Html.Raw(@Model.Template.Description)
            <p><strong>Author:</strong> @Model.Template.CreatedBy</p>
            <p><strong>Created At:</strong> @Model.Template.CreatedDate.ToShortDateString()</p>
            <p><strong>Likes:</strong> @Model.LikesCount</p>
            <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Forms", new { area = "Templates", id = Model.Template.TemplateId })">Start Test <i class='bx bx-right-arrow-alt'></i></a>

            <!-- Like Icon (no button box) -->
            <form asp-action="AddLike" method="post" class="mt-3" style="display: inline;">
                <input type="hidden" name="TemplateId" value="@Model.Template.TemplateId" />
                <button type="submit" class="like-icon" style="background: none; border: none; padding: 0;">
                    <i class="fas fa-thumbs-up fa-2x" style="cursor: pointer;"></i> (@Model.LikesCount)
                </button>
            </form>

        </div>
    </div>

    <hr />

    <!-- Tabs for Template Setup, Template Questions, and Submitted Form List -->
    <ul class="nav nav-tabs" id="templateTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "Setup" ? "active" : "")"
               id="setup-tab" data-toggle="tab" href="@Url.Action("SaveTemplate", "Template")" role="tab" aria-controls="setup" aria-selected="true">Template Setup</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "Questions" ? "active" : "")"
               id="questions-tab" data-toggle="tab" href="@Url.Action("TemplateQuestions", "Template")" role="tab" aria-controls="questions" aria-selected="false">Template Questions</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "SubmittedForms" ? "active" : "")"
               id="submitted-forms-tab" data-toggle="tab" href="@Url.Action("SubmittedForms","Template")" role="tab" aria-controls="submitted-forms" aria-selected="false">Submitted Forms</a>
        </li>
    </ul>

  @*   <ul class="nav nav-tabs" id="templateTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "Setup" ? "active" : "")"
               asp-action="SaveTemplate" asp-controller="Template" asp-area="Templates" role="tab" aria-controls="setup" aria-selected="true">Template Setup</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "Questions" ? "active" : "")"
               asp-action="AddTemplateQuestion" asp-controller="Question" asp-area="Templates" role="tab" aria-controls="questions" aria-selected="false">Template Questions</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link @(ViewData["ActiveTab"]?.ToString() == "SubmittedForms" ? "active" : "")"
               asp-action="SubmitForm" asp-controller="Form" asp-area="Templates" role="tab" aria-controls="submitted-forms" aria-selected="false">Submitted Forms</a>
        </li>
    </ul> *@


    <div class="tab-content" id="templateTabContent">
        <!-- Template Setup Tab -->
        <div class="tab-pane fade @(ViewData["ActiveTab"]?.ToString() == "Setup" ? "show active" : "")" id="setup" role="tabpanel" aria-labelledby="setup-tab">
            <h3>Template Setup</h3>
            <p>Here you can display and manage the template setup details.</p>
            <!-- Add more template setup content here -->
        </div>

        <!-- Template Questions Tab -->
        <div class="tab-pane fade @(ViewData["ActiveTab"]?.ToString() == "Questions" ? "show active" : "")" id="questions" role="tabpanel" aria-labelledby="questions-tab">
            <h3>Template Questions</h3>
            <p>Here you can display and manage the questions for this template.</p>
            <!-- Add questions-related content here -->
        </div>

        <!-- Submitted Forms Tab -->
        <div class="tab-pane fade @(ViewData["ActiveTab"]?.ToString() == "SubmittedForms" ? "show active" : "")" id="submitted-forms" role="tabpanel" aria-labelledby="submitted-forms-tab">
            <h3>Submitted Forms</h3>
            @if (Model.SubmittedForms != null && Model.SubmittedForms.Any())
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Submitted By</th>
                            <th>Submitted On</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var form in Model.SubmittedForms)
                        {
                            <tr>
                                <td>@form.SubmittedBy</td>
                                <td>@form.SubmittedDate.ToShortDateString()</td>
                                <td>
                                    <a href="@Url.Action("FormDetails", "Forms", new { formId = form.FormId })" class="btn btn-info btn-sm">View Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No forms have been submitted yet.</p>
            }
        </div>
    </div>

    <!-- Comment Section -->
    <h3>Comments</h3>
    <div class="comments-section mb-4">
        @if (Model.Comments != null && Model.Comments.Any())
        {
            @foreach (var comment in Model.Comments)
            {
                <div class="comment border p-3 rounded mb-3">
                    <p><strong>@comment.UserId:</strong> @comment.CommentText</p>
                    <p><small>Posted on: @comment.CreatedAt.ToString("MMMM dd, yyyy HH:mm")</small></p> <!-- Display exact date and time -->
                </div>
            }
        }
        else
        {
            <p>No comments yet. Be the first to comment!</p>
        }
    </div>

    <!-- Add Comment Form -->
    <form asp-action="AddComment" method="post" id="commentForm">
        <input type="hidden" name="TemplateId" value="@Model.Template.TemplateId" />
        <div class="form-group">
            <textarea id="commentText" name="CommentText" class="form-control" placeholder="Write a comment..." required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit Comment</button>
    </form>

    <script>
        document.getElementById('commentForm').addEventListener('submit', function (event) {
            var commentText = document.getElementById('commentText').value.trim();
            if (!commentText) {
                event.preventDefault(); // Prevent the form from submitting
                alert('Comment cannot be empty.');
            }
        });
    </script>

</div>

Areas/Templates/Views/Template/Index.cshtml
@model IEnumerable<ExamForms.ViewModel.TemplateViewModel>

<h1 class="text-center p-5">Templates</h1>

<a class="btn btn-outline-success" asp-action="SaveTemplate" asp-controller="Template" asp-area="Templates">Create New Template</a>

@{
    ViewData["Title"] = "All Templates";
}

<div class="container my-5">
    <h2 class="text-center mb-4">Available Templates</h2>
    <div class="row">
        @if (Model != null && Model.Any())
        {
            @foreach (var template in Model)
            {
                if (template != null && !string.IsNullOrEmpty(template.Title) && !string.IsNullOrEmpty(template.Image))
                {
                    <div class="col-md-3 mb-4">
                        <div class="card h-100 shadow-sm">
                            <img src="@template.Image" class="card-img-top" alt="Template Image" style="height:200px; object-fit:cover;" />
                            <div class="card-body">
                                <h5 class="card-title">@template.Title</h5>
                                @Html.Raw(@template.Description)
                                <p class="card-text"><small class="text-muted">Author: @template.CreatedBy</small></p>
                            </div>
                            <div class="card-footer d-flex justify-content-around">
                                <a href="@Url.Action("TemplateDetails", "Template", new { id = template.TemplateId })" class="btn btn-primary">View Details</a>
                                <a href="@Url.Action("SaveTemplate", "Template", new { area = "Templates", id = template.TemplateId })" id="editTemplateBtn" class="btn btn-warning">Edit</a>
                                <form asp-action="DeleteTemplate" asp-controller="Template" asp-area="Templates" method="post" onsubmit="return confirm('Are you sure you want to delete this template?');" style="display:inline;">
                                    <input type="hidden" name="id" value="@template.TemplateId" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
        }
        else
        {
            <div class="alert alert-warning text-center">
                No templates available at the moment.
            </div>
        }
    </div>
</div>

Areas/Templates/Views/Template/TemplateDetails.cshtml
@model ExamForms.ViewModel.TemplateViewModel

@{
    ViewData["Title"] = "Template Details";
}

<ul class="nav nav-tabs" id="templateTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="template-setup-tab" data-bs-toggle="tab" href="#template-setup" role="tab" aria-controls="template-setup" aria-selected="true">Setup</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="template-question-tab" data-bs-toggle="tab" href="#template-question" role="tab" aria-controls="template-question" aria-selected="false">Questions</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="template-form-tab" data-bs-toggle="tab" href="#template-form" role="tab" aria-controls="template-form" aria-selected="false">Forms</a>
    </li>
</ul>

<div class="tab-content" id="templateTabBody">
    <div class="tab-pane fade show active" id="template-setup" role="tabpanel" aria-labelledby="template-setup-tab">
        <div class="pt-3 pb-3">
            <div class="row">
                <div class="col-md-6">
                    <img src="@Model.Image" alt="Template Image" class="img-fluid rounded shadow-sm" style="max-height:400px; object-fit:cover;" />
                </div>

                <div class="col-md-6">
                    <h2 class="mb-3">@Model.Title</h2>
                    @Html.Raw(@Model.Description)
                    <p><strong>Author:</strong> @Model.CreatedBy</p>
                    <p><strong>Created At:</strong> @Model.CreatedDate.ToShortDateString()</p>
                    <p><strong>Likes:</strong> @Model.Likes.Count()</p>
                    <a class="btn btn-sm btn-success" href="@Url.Action("Index", "Forms", new { area = "Templates", id = Model.TemplateId })">Start Test <i class='bx bx-right-arrow-alt'></i></a>

                    <form asp-action="AddLike" method="post" class="mt-3" style="display: inline;">
                        <input type="hidden" name="TemplateId" value="@Model.TemplateId" />
                        <button type="submit" class="like-icon" style="background: none; border: none; padding: 0;">
                            <i class="fas fa-thumbs-up fa-2x" style="cursor: pointer;"></i> (@Model.Likes.Count())
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="template-question" role="tabpanel" aria-labelledby="template-question-tab">
        <div id="question_list_sortable_placeholder">
            <partial name="~/Areas/Templates/Views/Shared/_TemplateQuestionList.cshtml" model="@Model?.Questions" />
        </div>
    </div>

    <div class="tab-pane fade" id="template-form" role="tabpanel" aria-labelledby="template-form-tab">
        <div id="question_list_sortable_placeholder">
            <partial name="~/Areas/Templates/Views/Shared/_TemplateFormList.cshtml" model="@Model?.Forms" />
        </div>
    </div>
</div>




<!-- Comment Section -->
<h3>Comments</h3>
<div class="comments-section mb-4">
    @if (Model.Comments != null && Model.Comments.Any())
    {
        @foreach (var comment in Model.Comments)
        {
            <div class="comment border p-3 rounded mb-3">
                <p><strong>@comment.UserId:</strong> @comment.CommentText</p>
                <p><small>Posted on: @comment.CreatedAt.ToString("MMMM dd, yyyy HH:mm")</small></p> <!-- Display exact date and time -->
            </div>
        }
    }
    else
    {
        <p>No comments yet. Be the first to comment!</p>
    }
</div>

<div id="template_form_details_modal"></div>

<!-- Add Comment Form -->
<form asp-action="AddComment" method="post" id="commentForm">
    <input type="hidden" name="TemplateId" value="@Model.TemplateId" />
    <div class="form-group">
        <textarea id="commentText" name="CommentText" class="form-control" placeholder="Write a comment..." required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit Comment</button>
</form>

<script>
    document.getElementById('commentForm').addEventListener('submit', function (event) {
        var commentText = document.getElementById('commentText').value.trim();
        if (!commentText) {
            event.preventDefault(); // Prevent the form from submitting
            alert('Comment cannot be empty.');
        }
    });
</script>